"""Initial migration.

Revision ID: 552b654c0bb0
Revises: 
Create Date: 2023-10-10 22:34:08.335860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552b654c0bb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studentRegister', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studentRegister', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
